http:
  routers:
    immich:
      entryPoints:
        - websecure
      rule: Host("{{ env "IMMICH_DOMAIN" }}")
      tls:
        certResolver: ovh
      service: immich

  services:
    immich:
      loadBalancer:
        servers:
          - url: http://immich_server:2283
