services:
  certbot:
    image: certbot/certbot:latest
    volumes:
      - /docker_data/traefik/volumes/certbot/www/:/var/www/certbot/:rw
      - /docker_data/traefik/volumes/certbot/conf/:/etc/letsencrypt/:rw
