x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10MB"
      max-file: "10"

services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.7.12
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - /docker_data/tig_stack/volumes/influxdb_data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_PORT: "8086"
    # env_file:
    #   - ~/docker_data/tig_stack/configs/env_files/influxdb.env
    networks:
      - internal
      - traefik_global
    <<: *logging

  telegraf:
    container_name: telegraf
    image: telegraf:1.36.2
    restart: unless-stopped
    # bypass entrypoint because it always sets the user as telegraf
    # https://github.com/influxdata/influxdata-docker/blob/master/telegraf/1.34/entrypoint.sh
    entrypoint: ["/usr/bin/telegraf"]
    command: ["--config", "/etc/telegraf/telegraf.conf"]
    environment:
      HOST_ETC: /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS: /hostfs/sys
      HOST_VAR: /hostfs/var
      HOST_RUN: /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs

      INFLUXDB_TOKEN: "${INFLUXDB_TOKEN}"
      INFLUXDB_ORGANIZATION: "${INFLUXDB_ORGANIZATION}"
      TELEGRAF_INTERVAL: "${TELEGRAF_INTERVAL}"
      TELEGRAF_FILECOUNT_INTERVAL: "${TELEGRAF_FILECOUNT_INTERVAL}"
      BACKREST_DATA_DIR: "${BACKREST_DATA_DIR}"
      IMMICH_DATA_DIR: "${IMMICH_DATA_DIR}"
      NEXTCLOUD_DATA_DIR: "${NEXTCLOUD_DATA_DIR}"
      PIHOLE_DATA_DIR: "${PIHOLE_DATA_DIR}"
      PORTAINER_DATA_DIR: "${PORTAINER_DATA_DIR}"
      TIG_STACK_DATA_DIR: "${TIG_STACK_DATA_DIR}"
      TRAEFIK_DATA_DIR: "${TRAEFIK_DATA_DIR}"
      WIREGUARD_DATA_DIR: "${WIREGUARD_DATA_DIR}"
    volumes:
      - /dev:/dev
      - /var/run/docker.sock:/var/run/docker.sock
      # give +x permission to others to the parent directory of the
      # directories you want to scan!
      - /:/hostfs:ro
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    user: root
    network_mode: host
    <<: *logging

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:12.2.0-17142428006
    restart: unless-stopped
    volumes:
      - /docker_data/tig_stack/volumes/grafana_data:/var/lib/grafana
      - /docker_data/tig_stack/volumes/grafana_logs:/var/log/grafana
    environment:
      GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
    networks:
      - internal
      - traefik_global
    user: root
    <<: *logging

networks:
  internal:
  traefik_global:
    external: true
