x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10MB"
      max-file: "10"

name: portainer

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.33.2-alpine
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker_data/portainer/volumes/portainer_data:/data
    environment:
      AGENT_SECRET: "${AGENT_SECRET}"
    networks:
      internal:
      traefik_global:
    <<: *logging

  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent:2.33.2-alpine
    volumes:
      # Mount the host's Docker socket into the container
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the host's Docker volumes into the container
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host      
    environment:
      AGENT_SECRET: "${AGENT_SECRET}"
    restart: unless-stopped
    networks:
      internal:
    <<: *logging

networks:
  internal:
  traefik_global:
    external: true